name: Release

on:
  push:
    branches: 
      - 'feature/**'
      - main

env:
  SERVICE_NAME: 'toto-ms-tome-scraper'
  SERVICE_VERSION: '1.0.0'
  

jobs:
  # This workflow contains a single job called "release"
  release:
    name: Build & Deploy to GCP
    environment: totoexperiments
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Authenticate to Artifact Registry
      run: |
        echo '${{ secrets.CICD_SERVICE_ACCOUNT }}' > ./credentials.json
        gcloud auth activate-service-account --key-file=./credentials.json
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build . -t europe-west1-docker.pkg.dev/${{ vars.GCP_PID }}/${{env.SERVICE_NAME}}/${{env.SERVICE_NAME}}:${{env.SERVICE_VERSION}}
 
    - name: Push Docker image to Dockerhub 
      run: |
        docker push europe-west1-docker.pkg.dev/${{ vars.GCP_PID }}/${{env.SERVICE_NAME}}/${{env.SERVICE_NAME}}:${{env.SERVICE_VERSION}}

    - name: Setup GCloud 
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ vars.GCP_PID }}
        service_account_key: ${{ secrets.CICD_SERVICE_ACCOUNT }}
        export_default_credentials: true
    
    - name: Deploy image
      run: | 
        gcloud run deploy ${{env.SERVICE_NAME}} --set-env-vars "GCP_PID=${{ vars.GCP_PID }},BACKUP_BUCKET=${{ secrets.BACKUP_BUCKET }}" --service-account=${{ secrets.SERVICE_ACCOUNT }} --project=${{ vars.GCP_PID }} --image=europe-west1-docker.pkg.dev/${{ vars.GCP_PID }}/${{env.SERVICE_NAME}}/${{env.SERVICE_NAME}}:${{env.SERVICE_VERSION}} --platform=managed --region=europe-west1 --allow-unauthenticated